language: php

php:
  - 5.5

env:
  - SYMFONY_VERSION=3.0.1 

before_script:
  - composer install 
  - composer self-update
  - composer require symfony/symfony:3.0.1 

script: phpunit --coverage-text 